# Generated by Django 4.1.5 on 2023-01-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=244)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unique_code', models.CharField(max_length=244, unique=True)),
                ('size', models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30')])),
                ('quality', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.product')),
            ],
        ),
    ]
